// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Component defines model for Component.
type Component struct {
	AffectedBy  []Id   `json:"affectedBy"`
	DisplayName string `json:"displayName"`
	Id          string `json:"id"`
	Labels      Labels `json:"labels"`
}

// Id defines model for Id.
type Id = string

// Incident defines model for Incident.
type Incident struct {
	Affects    []Id               `json:"affects"`
	BeganAt    *time.Time         `json:"beganAt,omitempty"`
	EndedAt    *time.Time         `json:"endedAt"`
	Id         string             `json:"id"`
	ImpactType IncidentImpactType `json:"impactType"`
	Phase      IncidentPhase      `json:"phase"`
	Title      string             `json:"title"`
}

// IncidentImpactType defines model for IncidentImpactType.
type IncidentImpactType = string

// IncidentPhase defines model for IncidentPhase.
type IncidentPhase = string

// Labels defines model for Labels.
type Labels map[string]string

// GetIncidentsParams defines parameters for GetIncidents.
type GetIncidentsParams struct {
	// Start Start of time frame to query for (RFC3339)
	Start time.Time `form:"start" json:"start"`

	// End End of time frame to query for (RFC3339)
	End time.Time `form:"end" json:"end"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /components)
	GetComponents(ctx echo.Context) error
	// get specific component by id
	// (GET /components/{componentId})
	GetComponent(ctx echo.Context, componentId string) error

	// (GET /impacttypes)
	GetImpacttypes(ctx echo.Context) error
	// Get specific incident by id
	// (GET /incident/{incidentId})
	GetIncident(ctx echo.Context, incidentId string) error
	// Get list of incidents
	// (GET /incidents)
	GetIncidents(ctx echo.Context, params GetIncidentsParams) error

	// (GET /phases)
	GetPhases(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetComponents converts echo context to params.
func (w *ServerInterfaceWrapper) GetComponents(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetComponents(ctx)
	return err
}

// GetComponent converts echo context to params.
func (w *ServerInterfaceWrapper) GetComponent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "componentId" -------------
	var componentId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "componentId", runtime.ParamLocationPath, ctx.Param("componentId"), &componentId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter componentId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetComponent(ctx, componentId)
	return err
}

// GetImpacttypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetImpacttypes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetImpacttypes(ctx)
	return err
}

// GetIncident converts echo context to params.
func (w *ServerInterfaceWrapper) GetIncident(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "incidentId" -------------
	var incidentId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "incidentId", runtime.ParamLocationPath, ctx.Param("incidentId"), &incidentId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter incidentId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetIncident(ctx, incidentId)
	return err
}

// GetIncidents converts echo context to params.
func (w *ServerInterfaceWrapper) GetIncidents(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetIncidentsParams
	// ------------- Required query parameter "start" -------------

	err = runtime.BindQueryParameter("form", true, true, "start", ctx.QueryParams(), &params.Start)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start: %s", err))
	}

	// ------------- Required query parameter "end" -------------

	err = runtime.BindQueryParameter("form", true, true, "end", ctx.QueryParams(), &params.End)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetIncidents(ctx, params)
	return err
}

// GetPhases converts echo context to params.
func (w *ServerInterfaceWrapper) GetPhases(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPhases(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/components", wrapper.GetComponents)
	router.GET(baseURL+"/components/:componentId", wrapper.GetComponent)
	router.GET(baseURL+"/impacttypes", wrapper.GetImpacttypes)
	router.GET(baseURL+"/incident/:incidentId", wrapper.GetIncident)
	router.GET(baseURL+"/incidents", wrapper.GetIncidents)
	router.GET(baseURL+"/phases", wrapper.GetPhases)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWT4vbPhD9KmJ+v0ML7jrdnOrbNrSL6dKGprdlD4o1zmqxJa2kFEzwdy8jJ3b+1SsI",
	"hJ5iSzOj957ejLOBQtdGK1TeQbYBVzxjzcPjbLdBL8Zqg9ZLDFu8LLHwKD439CY91mH5f4slZPBfOtRM",
	"twXTXECbgG8MQgbcWt7Qu5DOVLz5zmukAttt561UK9qX4uxyxZdYvXnkQxfVtglYfF1LiwKyR6p5eHBf",
	"L9kn9tSj1csXLDydm5+Hk6tCihGh3IUqLXHF1V0oX2pbcw8ZCO7xg5cB/gkgVALFSIJaVxVfVgiZt2tM",
	"onWXteGF/xWW3yCylSQfMtoEzDN30anzEExySF+ds8e5e+1ik174A8w7AGev9hTw2FXPd0xOIh56b3Ih",
	"pJda8Wp+YIqTlCMwREyqUofYjjssZgu28NyvHZvzFbK7eQ4J/EbrpFaQwcebCVXSBhU3EjKY3kxubokx",
	"98/h1PSw0VcY7EG4OIEka8M9+tkQRfI6o5XrYN9OJvRTaOW3XufGVLII6emLIxy7ARJt+GHInPieZBDo",
	"CiuN70j++EarbbLPJd30z7loo5gFVSyv0aN1kD1uQFJ1Uop6I8wi2KsK+z7rGmZgeezJpwtVixTrL+Ik",
	"4NZ1zW0DGenAnMFClrJgfTW2bJgUITTtWoMYjFoi3wu7hifOz454c8htfrrZPb3hjH5+xxhjqPnP+KLH",
	"H2OL+31b7MgcuGK75mIkc6eaHZ6/8Nx6pktGnx5WUiTzmr2u0Tas1Ja9+/l1Np1OP72nWU0ZYWvQ21GB",
	"UaljvoltcgzsixKXwEIlLgf1dM12im6iY7dU0oUbHIwRfBK+paMmmXcR1yQ5/GmIGxdt+ycAAP//Wmmj",
	"dwILAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
